// Code generated by scache. DO NOT EDIT.
package {{.Package}}

import (
	"fmt"
	"sync"
	"time"

	"github.com/scache-io/scache"
	"github.com/scache-io/scache/config"
)

{{range .Structs}}
var (
	default{{.Name}}Scache *{{.Name}}Scache
	default{{.Name}}ScacheOnce sync.Once
)

type {{.Name}}Scache struct {
	cache *scache.LocalCache
}

func Get{{.Name}}Scache() *{{.Name}}Scache {
	default{{.Name}}ScacheOnce.Do(func() {
		default{{.Name}}Scache = New{{.Name}}Scache(nil)
	})
	return default{{.Name}}Scache
}

func New{{.Name}}Scache(cfg *config.EngineConfig) *{{.Name}}Scache {
	if cfg == nil {
		cfg = config.DefaultEngineConfig()
	}
	return &{{.Name}}Scache{
		cache: scache.New(cfg),
	}
}

func (s *{{.Name}}Scache) Store(key string, obj {{.Name}}, ttl ...time.Duration) error {
	return s.cache.Store(key, obj, ttl...)
}

func (s *{{.Name}}Scache) Load(key string) ({{.Name}}, error) {
	var obj {{.Name}}
	err := s.cache.Load(key, &obj)
	if err != nil {
		return obj, fmt.Errorf("key '%s' not found in cache: %w", key, err)
	}
	return obj, nil
}

func (s *{{.Name}}Scache) Delete(key string) bool {
	return s.cache.Delete(key)
}

func (s *{{.Name}}Scache) Clear() error {
	return s.cache.Flush()
}

func (s *{{.Name}}Scache) Size() int {
	return s.cache.Size()
}

func (s *{{.Name}}Scache) Keys() []string {
	return s.cache.Keys()
}

func (s *{{.Name}}Scache) Exists(key string) bool {
	return s.cache.Exists(key)
}

func (s *{{.Name}}Scache) SetTTL(key string, ttl time.Duration) bool {
	return s.cache.Expire(key, ttl)
}

func (s *{{.Name}}Scache) GetTTL(key string) (time.Duration, bool) {
	return s.cache.TTL(key)
}

func (s *{{.Name}}Scache) Stats() interface{} {
	return s.cache.Stats()
}

{{end}}
