// Code generated by scache. DO NOT EDIT.
package {{.Package}}

import (
	"fmt"
	"sync"
	"time"

	"github.com/scache-io/scache"
	"github.com/scache-io/scache/config"
)

{{range .Structs}}
var (
	default{{.Name}}Scache *{{.Name}}Scache
	default{{.Name}}ScacheOnce sync.Once
)

type {{.Name}}Scache struct {
	cache *scache.LocalCache
}

func Get{{.Name}}Scache() *{{.Name}}Scache {
	default{{.Name}}ScacheOnce.Do(func() {
		default{{.Name}}Scache = New{{.Name}}Scache()
	})
	return default{{.Name}}Scache
}

func New{{.Name}}Scache(opts ...config.EngineOption) *{{.Name}}Scache {
	return &{{.Name}}Scache{
		cache: scache.New(opts...),
	}
}

func (s *{{.Name}}Scache) Store(key string, obj {{.Name}}, ttl ...time.Duration) error {
	return s.cache.Store(key, obj, ttl...)
}

func (s *{{.Name}}Scache) Load(key string) ({{.Name}}, error) {
	var obj {{.Name}}
	err := s.cache.Load(key, &obj)
	if err != nil {
		return {{.Name}}{}, fmt.Errorf("key '%s' not found in cache: %w", key, err)
	}
	return obj, nil
}

func (s *{{.Name}}Scache) Delete(key string) error {
	s.cache.Delete(key)
	return nil
}

func (s *{{.Name}}Scache) Clear() error {
	return s.cache.Flush()
}

func (s *{{.Name}}Scache) Size() int {
	return s.cache.Size()
}

func (s *{{.Name}}Scache) Keys() []string {
	return s.cache.Keys()
}

func (s *{{.Name}}Scache) Exists(key string) bool {
	return s.cache.Exists(key)
}

func (s *{{.Name}}Scache) SetTTL(key string, ttl time.Duration) error {
	success := s.cache.Expire(key, ttl)
	if !success {
		return fmt.Errorf("failed to set TTL for key '%s'", key)
	}
	return nil
}

func (s *{{.Name}}Scache) GetTTL(key string) (time.Duration, bool) {
	return s.cache.TTL(key)
}

{{end}}