// Code generated by scache. DO NOT EDIT.
package {{.Package}}

import (
	"fmt"
	"sync"
	"time"

	"github.com/scache-io/scache"
	"github.com/scache-io/scache/config"
)

{{range .Structs}}
var (
	default{{.Name}}Scache *Scache[{{.Name}}]
	default{{.Name}}ScacheOnce sync.Once
)
{{end}}

type Scache[T any] struct {
	cache *scache.LocalCache
}

{{range .Structs}}
func Get{{.Name}}Scache() *Scache[{{.Name}}] {
	default{{.Name}}ScacheOnce.Do(func() {
		default{{.Name}}Scache = NewScache[{{.Name}}](nil)
	})
	return default{{.Name}}Scache
}

func New{{.Name}}Scache(cfg *config.EngineConfig) *Scache[{{.Name}}] {
	return NewScache[{{.Name}}](cfg)
}
{{end}}

func NewScache[T any](cfg *config.EngineConfig) *Scache[T] {
	if cfg == nil {
		cfg = config.DefaultEngineConfig()
	}
	return &Scache[T]{
		cache: scache.New(cfg),
	}
}

func (s *Scache[T]) Store(key string, obj T, ttl ...time.Duration) error {
	return s.cache.Store(key, obj, ttl...)
}

func (s *Scache[T]) Load(key string) (T, error) {
	var obj T
	err := s.cache.Load(key, &obj)
	if err != nil {
		return obj, fmt.Errorf("key '%s' not found in cache: %w", key, err)
	}
	return obj, nil
}

func (s *Scache[T]) Delete(key string) bool {
	return s.cache.Delete(key)
}

func (s *Scache[T]) Exists(key string) bool {
	return s.cache.Exists(key)
}

func (s *Scache[T]) SetTTL(key string, ttl time.Duration) bool {
	return s.cache.Expire(key, ttl)
}

func (s *Scache[T]) GetTTL(key string) (time.Duration, bool) {
	return s.cache.TTL(key)
}

func (s *Scache[T]) Clear() error {
	return s.cache.Flush()
}

func (s *Scache[T]) Size() int {
	return s.cache.Size()
}

func (s *Scache[T]) Keys() []string {
	return s.cache.Keys()
}

func (s *Scache[T]) Stats() interface{} {
	return s.cache.Stats()
}
