package generator

import (
	_ "embed"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

//go:embed cache.tpl
var cacheTemplateContent string

//go:embed cache_generic.tpl
var cacheGenericTemplateContent string

// Config Generator configuration
type Config struct {
	Dir            string   // Scan directory
	Package        string   // Package name
	ExcludeDirs    []string // Directories to exclude
	TargetStructs  []string // Specific struct names
	SplitPackages  bool     // Split by package
	GeneratedCount int      // Number of generated structs
	UseGeneric     bool     // Use generic version
}

// StructInfo Struct information
type StructInfo struct {
	Name   string      // Struct name
	Fields []FieldInfo // Field information
	Pkg    string      // Package name
	Source string      // Source file path
}

// FieldInfo Field information
type FieldInfo struct {
	Name string // Field name
	Type string // Field type
	Tag  string // Tag
}

// Generate Execute code generation
func Generate(config *Config) error {
	// Scan structs
	structs, err := scanStructs(config)
	if err != nil {
		return fmt.Errorf("failed to scan structs: %w", err)
	}

	if len(structs) == 0 {
		return fmt.Errorf("No structs found")
	}

	// Filter specified structs
	if len(config.TargetStructs) > 0 {
		filtered := make([]StructInfo, 0)
		structMap := make(map[string]StructInfo)
		for _, s := range structs {
			structMap[s.Name] = s
		}
		for _, target := range config.TargetStructs {
			if s, exists := structMap[target]; exists {
				filtered = append(filtered, s)
			}
		}
		structs = filtered
	}

	if len(structs) == 0 {
		return fmt.Errorf("Specified structs not found")
	}

	// Record number of generated structs
	config.GeneratedCount = len(structs)

	// Generate file in same directory, no package splitting
	return generateInPlace(config, structs)
}

// scanStructs Scan directoryall structs in
func scanStructs(config *Config) ([]StructInfo, error) {
	var structs []StructInfo
	fset := token.NewFileSet()

	err := filepath.Walk(config.Dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// Skip directory
		if info.IsDir() {
			// Check if should exclude
			for _, exclude := range config.ExcludeDirs {
				if strings.Contains(path, exclude) {
					return filepath.SkipDir
				}
			}
			return nil
		}

		// Only process .go files
		if !strings.HasSuffix(path, ".go") {
			return nil
		}

		// Skip test files
		if strings.HasSuffix(path, "_test.go") {
			return nil
		}

		// Skip generated files (scache generated)
		if isScacheGeneratedFile(path) {
			return nil
		}

		// Parse Go file
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil // Ignore files with parse errors
		}

		// Extract structs
		fileStructs := extractStructs(file, path)
		structs = append(structs, fileStructs...)

		return nil
	})

	return structs, err
}

// extractStructs Extract structs from AST
func extractStructs(file *ast.File, sourcePath string) []StructInfo {
	var structs []StructInfo

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			// 提取Field information
			var fields []FieldInfo
			if structType.Fields != nil {
				for _, field := range structType.Fields.List {
					fieldInfo := FieldInfo{}

					// Field name
					if len(field.Names) > 0 {
						fieldInfo.Name = field.Names[0].Name
					} else {
						// Anonymous field
						fieldInfo.Name = ""
					}

					// Field type
					fieldInfo.Type = fieldTypeToString(field.Type)

					// Tag
					if field.Tag != nil {
						fieldInfo.Tag = strings.Trim(field.Tag.Value, "`")
					}

					fields = append(fields, fieldInfo)
				}
			}

			structs = append(structs, StructInfo{
				Name:   typeSpec.Name.Name,
				Fields: fields,
				Pkg:    file.Name.Name,
				Source: sourcePath,
			})
		}
	}

	return structs
}

// fieldTypeToString Convert field type to string
func fieldTypeToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return fmt.Sprintf("%s.%s", fieldTypeToString(t.X), t.Sel.Name)
	case *ast.ArrayType:
		return fmt.Sprintf("[]%s", fieldTypeToString(t.Elt))
	case *ast.StarExpr:
		return fmt.Sprintf("*%s", fieldTypeToString(t.X))
	case *ast.MapType:
		return fmt.Sprintf("map[%s]%s", fieldTypeToString(t.Key), fieldTypeToString(t.Value))
	case *ast.InterfaceType:
		return "interface{}"
	case *ast.Ellipsis:
		return fmt.Sprintf("...%s", fieldTypeToString(t.Elt))
	default:
		return "unknown"
	}
}

// isScacheGeneratedFile Check if file is generated by scache
func isScacheGeneratedFile(path string) bool {
	file, err := os.Open(path)
	if err != nil {
		return false
	}
	defer file.Close()

	// Read first 1KB to check for generated marker
	buf := make([]byte, 1024)
	n, err := file.Read(buf)
	if err != nil {
		return false
	}

	content := string(buf[:n])
	return strings.Contains(content, "Code generated by scache. DO NOT EDIT.")
}

// generateInPlace Generate _scache.go file in same directory
func generateInPlace(config *Config, structs []StructInfo) error {
	// Group structs by package
	packageGroups := make(map[string][]StructInfo)
	for _, structInfo := range structs {
		packageGroups[structInfo.Pkg] = append(packageGroups[structInfo.Pkg], structInfo)
	}

	// Generate _scache.go file for each package
	for pkgName, pkgStructs := range packageGroups {
		if err := generatePackageScache(config, pkgName, pkgStructs); err != nil {
			return err
		}
	}

	return nil
}

// generatePackageScache Generate _scache.go file for specified package
func generatePackageScache(config *Config, pkgName string, structs []StructInfo) error {
	// Find directory of first struct in package
	targetDir := findPackageDirectory(pkgName, structs)
	if targetDir == "" {
		return fmt.Errorf("package directory not found: %s", pkgName)
	}

	// Generate filename
	filename := filepath.Join(targetDir, pkgName+"_scache.go")

	// Generate package code
	content, err := generatePackageCode(pkgName, structs, config.UseGeneric)
	if err != nil {
		return fmt.Errorf("Failed to generate code: %w", err)
	}

	// Write file
	return generatePackageFile(filename, content)
}

// findPackageDirectory Find package directory
func findPackageDirectory(pkgName string, structs []StructInfo) string {
	for _, structInfo := range structs {
		if structInfo.Pkg == pkgName {
			return filepath.Dir(structInfo.Source)
		}
	}
	return ""
}

// TemplateData Template data structure
type TemplateData struct {
	Package string
	Structs []StructInfo
}

// loadTemplate Load template file
func loadTemplate(useGeneric bool) (*template.Template, error) {
	templateName := "cache"
	templateContent := cacheTemplateContent

	if useGeneric {
		templateName = "cache_generic"
		templateContent = cacheGenericTemplateContent
	}

	return template.New(templateName).Parse(templateContent)
}

// generatePackageCode Generate cache code for specified package
func generatePackageCode(pkgName string, structs []StructInfo, useGeneric bool) (string, error) {
	// Load embedded template
	tmpl, err := loadTemplate(useGeneric)
	if err != nil {
		return "", fmt.Errorf("Failed to load template: %w", err)
	}

	data := TemplateData{
		Package: pkgName,
		Structs: structs,
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("Failed to execute template: %w", err)
	}

	return buf.String(), nil
}

// generatePackageFile Generate package file
func generatePackageFile(filePath, content string) error {
	// Ensure directory exists
	dir := filepath.Dir(filePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("Failed to create directory: %w", err)
	}

	// Check if file exists, delete if it does
	if _, err := os.Stat(filePath); err == nil {
		if removeErr := os.Remove(filePath); removeErr != nil {
			return fmt.Errorf("failed to remove existing file: %w", removeErr)
		}
	}

	// Write file
	if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	// Format generated file
	_ = formatGoFile(filePath) // Ignore format errors

	return nil
}

// formatGoFile Format Go file
func formatGoFile(filePath string) error {
	// Execute go fmt command
	cmd := exec.Command("go", "fmt", filePath)
	output, err := cmd.CombinedOutput()

	if err != nil {
		return fmt.Errorf("go fmt failed: %v, output: %s", err, string(output))
	}

	return nil
}
